//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoFrame {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SystemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoFrame.SystemResource", typeof(SystemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PointCfg&gt;
        ///  &lt;测试1站&gt;
        ///    &lt;Point index=&quot;1&quot; name=&quot;安全点&quot; x=&quot;100&quot; y=&quot;0&quot; z=&quot;0&quot; u=&quot;0&quot; a=&quot;300&quot; b=&quot;0&quot; c=&quot;0&quot; d=&quot;0&quot; /&gt;
        ///    &lt;Point index=&quot;2&quot; name=&quot;拍照点&quot; x=&quot;0&quot; y=&quot;10&quot; z=&quot;0&quot; u=&quot;0&quot; a=&quot;0&quot; b=&quot;400&quot; c=&quot;0&quot; d=&quot;0&quot; /&gt;
        ///    &lt;Point index=&quot;3&quot; name=&quot;取料点&quot; x=&quot;0&quot; y=&quot;0&quot; z=&quot;10&quot; u=&quot;10&quot; a=&quot;0&quot; b=&quot;0&quot; c=&quot;500&quot; d=&quot;0&quot; /&gt;
        ///  &lt;/测试1站&gt;
        ///  &lt;测试2站&gt;
        ///    &lt;Point index=&quot;1&quot; name=&quot;SafePoint&quot; x=&quot;10&quot; y=&quot;0&quot; z=&quot;0&quot; u=&quot;0&quot; a=&quot;0&quot; b=&quot;30&quot; c=&quot;0&quot; d=&quot;0&quot; /&gt;
        ///  &lt;/测试2站&gt;
        ///&lt;/PointCfg&gt; 的本地化字符串。
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SystemCfg&gt;
        ///  &lt;SystemParamName&gt;
        ///    &lt;SystemParamName 系统参数文件名=&quot;systemParam.xml&quot; /&gt;
        ///  &lt;/SystemParamName&gt;
        ///  &lt;IoCard&gt;
        ///    &lt;IoCard 卡序号=&quot;1&quot; 卡号=&quot;0&quot; 卡类型=&quot;8254&quot; /&gt;
        ///    &lt;IoCard 卡序号=&quot;2&quot; 卡号=&quot;1&quot; 卡类型=&quot;8254&quot; /&gt;
        ///    &lt;IoCard 卡序号=&quot;3&quot; 卡号=&quot;2&quot; 卡类型=&quot;8254&quot; /&gt;
        ///    &lt;IoCard 卡序号=&quot;4&quot; 卡号=&quot;0&quot; 卡类型=&quot;0640A&quot; /&gt;
        ///    &lt;IoCard 卡序号=&quot;5&quot; 卡号=&quot;1&quot; 卡类型=&quot;0640A&quot; /&gt;
        ///    &lt;IoCard 卡序号=&quot;6&quot; 卡号=&quot;2&quot; 卡类型=&quot;0640A&quot; /&gt;
        ///  &lt;/IoCard&gt;
        ///  &lt;IoIn&gt;
        ///    &lt;IoIn 卡序号=&quot;1&quot; 点序号=&quot;1&quot; 点位名称=&quot;急停&quot; 点位翻译=&quot;EStop&quot; /&gt;
        ///    &lt;IoIn 卡序号=&quot;1&quot; 点序号= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SystemCfg {
            get {
                return ResourceManager.GetString("SystemCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SystemCfg&gt;
        ///  &lt;Opc&gt;
        ///    &lt;Opc 服务器IP=&quot;&quot; 服务器名称=&quot;KEPware.KEPServerEx.V4&quot; 组名称=&quot;PLC&quot; 刷新频率=&quot;250&quot; 启用=&quot;False&quot; /&gt;
        ///  &lt;/Opc&gt;
        ///  &lt;Data&gt;
        ///    &lt;Data 名称=&quot;组装精度&quot; 版本=&quot;1.0&quot; PDCA=&quot;False&quot; 权限=&quot;2&quot;&gt;
        ///      &lt;Item 名称=&quot;X&quot; 数据类型=&quot;&quot; 数据索引=&quot;&quot; 标准值=&quot;0.54&quot; 上限=&quot;0.59&quot; 下限=&quot;0.49&quot; 补偿值=&quot;0&quot; 单位=&quot;mm&quot; /&gt;
        ///      &lt;Item 名称=&quot;Y&quot; 数据类型=&quot;&quot; 数据索引=&quot;&quot; 标准值=&quot;2.52&quot; 上限=&quot;2.59&quot; 下限=&quot;2.47&quot; 补偿值=&quot;0&quot; 单位=&quot;mm&quot; /&gt;
        ///      &lt;Item 名称=&quot;Z&quot; 数据类型=&quot;&quot; 数据索引=&quot;&quot; 标准值=&quot;0&quot; 上限=&quot;0&quot; 下限=&quot;0&quot; 补偿值=&quot;0&quot; 单位=&quot;mm&quot; /&gt;
        ///      &lt;Item 名称=&quot;U&quot; 数据类型=&quot;&quot; 数据索引=&quot;&quot; 标准值=&quot;0&quot; 上限 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SystemCfgEx {
            get {
                return ResourceManager.GetString("SystemCfgEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;SystemParam&gt;
        ///  &lt;ParamDescribe&gt;
        ///    &lt;ParamDescribe 修改者=&quot;Admin&quot; 文件描述=&quot;系统配置参数-运行用&quot; /&gt;
        ///  &lt;/ParamDescribe&gt;
        ///  &lt;Param&gt;
        ///    &lt;Param 键值=&quot;RunParam&quot; 当前值=&quot;&quot; 单位=&quot;&quot; 参数描述=&quot;-----------运行参数设置-----------&quot; 翻译=&quot;---Operation parameter setting---&quot; 最小值=&quot;&quot; 最大值=&quot;&quot; /&gt;
        ///    &lt;Param 键值=&quot;AxisXSpeed&quot; 当前值=&quot;10&quot; 单位=&quot;%&quot; 参数描述=&quot;X轴速度(速度百分比)&quot; 翻译=&quot;X-axis speed (speed percentage)&quot; 最小值=&quot;0.1&quot; 最大值=&quot;100&quot; /&gt;
        ///    &lt;Param 键值=&quot;AxisYSpeed&quot; 当前值=&quot;10&quot; 单位=&quot;%&quot; 参数描述=&quot;Y轴速度(速度百分比)&quot; 翻译=&quot;Y-axis speed (speed percentage)&quot; 最 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string systemParam {
            get {
                return ResourceManager.GetString("systemParam", resourceCulture);
            }
        }
    }
}
